services:
  hops:
    build: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../hops-test:/git/hops-test # Same as git@github.com:HBDK/test-repo.git
      - ~/.ssh:/root/.ssh
